"""WorldForgeZero PocketWorld Engine (C extension)."""

class Coordinate:
    x: int
    y: int
    def __init__(self, x: int, y: int) -> None: ...

class Vector2D:
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    def __init__(self, x: int = 0, y: int = 0) -> None: ...
    def __add__(self, other: Vector2D) -> Vector2D: ...
    def __sub__(self, other: Vector2D) -> Vector2D: ...
    def __mul__(self, value: int) -> Vector2D: ...
    def __truediv__(self, value: int) -> Vector2D: ...

class Entity:
    @property
    def id(self) -> int: ...
    @property
    def type(self) -> int: ...
    @property
    def flags(self) -> int: ...
    anchor: Coordinate
    rotation: int
    vel: Vector2D
    width: int
    height: int
    def GetOccupiedTiles(self) -> list[Coordinate]: ...
    def HasFlag(self, flag: int) -> bool: ...
    def AddFlag(self, flag: int) -> None: ...
    def RemoveFlag(self, flag: int) -> None: ...

class Tile:
    localX: int
    localY: int
    def GetOccupyingEntities(self) -> list[Entity]: ...

class Chunk:
    def GetX(self) -> int: ...
    def GetY(self) -> int: ...
    def GetTile(self, localX: int, localY: int) -> Tile: ...
    def GetEntities(self) -> list[Entity]: ...

class World:
    def __init__(self) -> None: ...
    def GetChunk(self, globalX: int, globalY: int) -> Chunk | None: ...
    def GetOrCreateChunk(self, globalX: int, globalY: int) -> Chunk: ...
    def RemoveChunk(self, globalX: int, globalY: int) -> None: ...

class EntityManager:
    def __init__(self) -> None: ...
    def SpawnEntity(
        self,
        world: World,
        type: int,
        flags: int,
        anchor: Coordinate,
        rotation: int = 0,
        width: int = 1,
        height: int = 1,
    ) -> int: ...
    def RemoveEntity(self, world: World, id: int) -> None: ...
    def MoveEntity(self, world: World, id: int, newAnchor: Coordinate) -> bool: ...
    def GetEntity(self, id: int) -> Entity | None: ...

# Константы
ENTITY_SOLID: int
ENTITY_FLOOR: int
